# This is a basic workflow to help you get started with Actions

name: Hexo Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Use node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup hexo env
        run: |
          npm install hexo-cli -g
          npm install
          npm install hexo-theme-next

      - name: Generate static pages
        run: |
          hexo clean
          hexo g  

      # from https://github.com/peaceiris/actions-gh-pages    
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}    
